Repository ContentSquare/readapt, pull requests merged in 2022-06, with the labels that each got.

#2 release v1.0.0
  apps/chrome-extension/package.json
  apps/ms-word-addin/package.json
  lerna.json
  packages/dictionaries/package.json
  packages/settings/package.json
  packages/shared-components/package.json
  packages/shared-components/tests/unit/RangeBar.spec.ts
  packages/shared-components/tests/unit/SelectPercentage.spec.ts
  packages/shared-components/tsconfig.json
  packages/text-engine/package.json
  packages/visual-engine/package.json
Labels: size/M

#4 Chrome first run
  apps/chrome-extension/src/components/QuickActivate.vue
  apps/chrome-extension/src/i18n/en.json
  apps/chrome-extension/src/i18n/fr.json
  apps/chrome-extension/src/views/MainMenu.vue
Labels: size/M

#9 Feat chrome extension metrics
  .gitignore
  apps/chrome-extension/.env-template
  apps/chrome-extension/README.md
  apps/chrome-extension/package.json
  apps/chrome-extension/scripts/init-env
  apps/chrome-extension/src-extension/background.ts
  apps/chrome-extension/src-extension/readapt.ts
  apps/chrome-extension/src-extension/rollup.config.js
  package.json
  yarn.lock
Labels: size/M

#10 feat(ms-word-addin): collects adapt event metrics
  apps/ms-word-addin/.env-template
  apps/ms-word-addin/package.json
  apps/ms-word-addin/scripts/init-env
  apps/ms-word-addin/src/constants/config.ts
  apps/ms-word-addin/src/services/stats.ts
  apps/ms-word-addin/src/views/MainMenu.vue
Labels: size/M

#14 build(chrome-extension): update description in manifest.json
  apps/chrome-extension/manifest.json
Labels: size/XS

#15 Feat chrome UI fix
  apps/chrome-extension/src/views/MainMenu.vue
Labels: size/XS

#5 feat: add dynamic text preview
  apps/chrome-extension/package.json
  apps/chrome-extension/src/components/AdaptContainer.vue
  apps/chrome-extension/src/components/PreviewContainer.vue
  apps/chrome-extension/src/components/TemplateSelectorOption.vue
  apps/chrome-extension/src/main.ts
  apps/chrome-extension/src/shims-vue.d.ts
  apps/chrome-extension/src/views/SettingsMenu.vue
  apps/ms-word-addin/package.json
  apps/ms-word-addin/src/components/AdaptContainer.vue
  apps/ms-word-addin/src/components/PreviewContainer.vue
  apps/ms-word-addin/src/main.ts
  apps/ms-word-addin/src/shims-vue.d.ts
  apps/ms-word-addin/src/views/DialogBox.vue
  apps/ms-word-addin/src/views/SettingsMenu.vue
  packages/settings/src/langConfig/langConfigEn.ts
  packages/settings/src/langConfig/langConfigFr.ts
  yarn.lock
Labels: size/L

#17 fix: double adaptation in AdaptContainer
  apps/chrome-extension/src/components/AdaptContainer.vue
  apps/ms-word-addin/src/components/AdaptContainer.vue
Labels: size/XS

#18 feat: ms word addin images
  .github/workflows/main.yaml
  apps/chrome-extension/package.json
  apps/chrome-extension/src/components/QuickActivate.vue
  apps/ms-word-addin/package.json
  apps/ms-word-addin/public/assets/no-image.png
  apps/ms-word-addin/src/views/DialogBox.vue
  apps/ms-word-addin/src/views/MainMenu.vue
  packages/settings/src/options/index.ts
  packages/settings/src/options/thicknessOptions.ts
Labels: size/L

#19 build: add a status badge in the readme
  .github/CODEOWNERS
  Makefile
  README.md
Labels: size/M
