Repository ContentSquare/readapt, pull requests merged in 2022-07, with the labels that each got.

#21 fix: pull up <p> tag to parent component in AdaptContainer
  apps/chrome-extension/src/components/AdaptContainer.vue
  apps/chrome-extension/src/components/PreviewContainer.vue
  apps/chrome-extension/src/components/TemplateSelectorOption.vue
  apps/ms-word-addin/src/components/AdaptContainer.vue
  apps/ms-word-addin/src/components/PreviewContainer.vue
Labels: size/M

#22 feat(ms-word-addin): adapt selected text
  apps/ms-word-addin/src/i18n/en.json
  apps/ms-word-addin/src/i18n/fr.json
  apps/ms-word-addin/src/views/DialogBox.vue
  apps/ms-word-addin/src/views/MainMenu.vue
Labels: size/M

#23 refactor: ms word addin components
  apps/chrome-extension/src/components/AdaptContainer.vue
  apps/ms-word-addin/src/components/AdaptContainer.vue
  apps/ms-word-addin/src/components/PreviewContainer.vue
  apps/ms-word-addin/src/views/DialogBox.vue
  apps/ms-word-addin/src/views/SettingsMenu.vue
Labels: size/L

#27 build: bump lerna to 5.1.x
  package.json
  yarn.lock
Labels: size/XXL

#26 fix(ms-word-addin): move <img> elements outside <p> elements to avoid…
  apps/ms-word-addin/src/views/MainMenu.vue
Labels: size/S

#25 feat optimize ms word addin UI
  apps/ms-word-addin/src/components/PreviewContainer.vue
  apps/ms-word-addin/src/i18n/en.json
  apps/ms-word-addin/src/i18n/fr.json
  apps/ms-word-addin/src/views/SettingsMenu.vue
  apps/ms-word-addin/src/views/SettingsMenuGeneral.vue
  apps/ms-word-addin/src/views/SettingsMenuLetters.vue
  apps/ms-word-addin/src/views/SettingsMenuPhonemes.vue
  packages/visual-engine/src/buildItemPreview.ts
Labels: size/L

#32 refactor shared components
  apps/chrome-extension/src/components/PreviewContainer.vue
  apps/chrome-extension/src/components/TemplateSelectorOption.vue
  apps/chrome-extension/src/constants/defaultProfiles.ts
  apps/chrome-extension/src/interfaces/index.ts
  apps/chrome-extension/src/interfaces/settingsTemplate.ts
  apps/chrome-extension/src/router/index.ts
  apps/chrome-extension/src/router/router.ts
  apps/chrome-extension/src/store/index.ts
  apps/chrome-extension/src/store/storage.ts
  apps/chrome-extension/src/store/store.ts
  apps/chrome-extension/src/views/MainMenu.vue
  apps/chrome-extension/src/views/SettingsMenu.vue
  apps/chrome-extension/src/views/SettingsMenuGeneral.vue
  apps/chrome-extension/src/views/SettingsMenuLetters.vue
  apps/chrome-extension/src/views/SettingsMenuPhonemes.vue
  apps/chrome-extension/src/views/TemplateSelect.vue
  apps/chrome-extension/src/visualEngine/adaptHtmlElementAsync.ts
  apps/ms-word-addin/src/components/AdaptContainer.vue
  apps/ms-word-addin/src/components/PreviewContainer.vue
  apps/ms-word-addin/src/constants/defaultProfiles.ts
  apps/ms-word-addin/src/interfaces/index.ts
  apps/ms-word-addin/src/interfaces/profiles.ts
  apps/ms-word-addin/src/router/index.ts
  apps/ms-word-addin/src/router/router.ts
  apps/ms-word-addin/src/store/index.ts
  apps/ms-word-addin/src/store/storage.ts
  apps/ms-word-addin/src/store/store.ts
  apps/ms-word-addin/src/views/DialogBox.vue
  apps/ms-word-addin/src/views/MainMenu.vue
  apps/ms-word-addin/src/views/SettingsMenu.vue
  apps/ms-word-addin/src/views/SettingsMenuGeneral.vue
  apps/ms-word-addin/src/views/SettingsMenuLetters.vue
  apps/ms-word-addin/src/views/SettingsMenuPhonemes.vue
  apps/ms-word-addin/src/visualEngine/adaptHtmlElementAsync.ts
  packages/settings/src/defaultProfiles.ts
  packages/settings/src/index.ts
  packages/settings/src/models/index.ts
  packages/settings/src/models/profiles.ts
  packages/settings/src/models/settings.ts
  packages/settings/src/models/storeModel.ts
  packages/shared-components/package.json
  packages/shared-components/src/components/adapt/AdaptContainer.vue
  packages/shared-components/src/components/adapt/PreviewContainer.vue
  packages/shared-components/src/index.ts
  packages/shared-components/src/sharedStoreOptions.ts
  packages/shared-components/tests/unit/PreviewContainer.spec.ts
Labels: size/XXL

#36 Feat/i18n selector
  apps/chrome-extension/src/i18n/en.json
  apps/chrome-extension/src/i18n/fr.json
  apps/ms-word-addin/src/i18n/en.json
  apps/ms-word-addin/src/i18n/fr.json
  packages/settings/src/options/fontSizeOptions.ts
  packages/settings/src/options/letterSpacingOptions.ts
  packages/settings/src/options/lineSpacingOptions.ts
  packages/settings/src/options/wordSpacingOptions.ts
  packages/shared-components/package.json
  packages/shared-components/src/components/forms/SelectPercentage.vue
  packages/shared-components/tests/unit/SelectPercentage.spec.ts
Labels: size/M

#35 refactor(ms-word-addin): refactor reading tools
  apps/ms-word-addin/src/views/DialogBox.vue
Labels: size/L

#34 fix(chrome-extension): typo
  apps/chrome-extension/src/i18n/en.json
  apps/chrome-extension/src/i18n/fr.json
  apps/chrome-extension/src/views/SettingsMenuGeneral.vue
Labels: size/XS

#40 v1.3.0
  apps/chrome-extension/package.json
  apps/ms-word-addin/package.json
  lerna.json
  packages/dictionaries/package.json
  packages/settings/package.json
  packages/shared-components/package.json
  packages/text-engine/package.json
  packages/visual-engine/package.json
Labels: size/M
